from p7 import *

# 1
print("1.")
print("1.1")
print("raizDe2(): " + str(raizDe2()))
print("1.2")
imprimir_hola()
print("1.3")
imprimir_un_verso()
print("1.4")
print("factorial_de_dos(): " +  str(factorial_de_dos()))
print("1.5")
print("factorial_3(): " + str(factorial_3()))
print("1.6")
print("factorial_4(): " + str(factorial_4()))
print("1.7")
print("factorial_5(): " + str(factorial_5()))

print("-----")

print("2.")
print("2.1")
imprimir_saludo("Pablo")
print("2.2")
print("raiz_cuadrada_de(16.0): " + str(raiz_cuadrada_de(16.0)))
print("raiz_cuadrada_de(2): " + str(raiz_cuadrada_de(2)))
print("2.3")
imprimir_dos_veces('Nuevos discos, nuevas drogas\n')
print("2.4")
print("es_multiplo_de(6,2): " + str(es_multiplo_de(6,2)))
print("es_multiplo_de(7,5): " + str(es_multiplo_de(7,5)))
print("es_multiplo_de(0,3891): " + str(es_multiplo_de(0,3891)))
print("2.5")
print("es_par(12): ", str(es_par(12)))
print("es_par(7): ", str(es_par(7)))
print("2.6")
print("cantidad_de_pizzas(2,9): " + str(cantidad_de_pizzas(2,9)))
print("cantidad_de_pizzas(6,3): " + str(cantidad_de_pizzas(2,9)))

print("-----")

print("3.")
print("3.1")
print("alguno_es_0(0,1): " + str(alguno_es_0(0,1)))
print("alguno_es_0(1,1): " + str(alguno_es_0(1,1)))
print("3.2")
print("ambos_son_0(0,0): " + str(ambos_son_0(0,0)))
print("ambos_son_0(1,0): " + str(ambos_son_0(1,0)))
print("3.3")
print('es_nombre_largo("Ki"): ' + str(es_nombre_largo("Ki")))
print('es_nombre_largo("Gustavo"): ' + str(es_nombre_largo("Gustavo")))
print("3.4")
print("es_bisiesto(2000): " + str(es_bisiesto(2000)))
print("es_bisiesto(2001): " + str(es_bisiesto(2001)))

print("-----")

print("4")
print("4.1")
print("peso_pino(2): " + str(peso_pino(2)))
print("peso_pino(5): " + str(peso_pino(5)))
print("4.2")
print("es_peso_util(300): " + str(es_peso_util(300)))
print("es_peso_util(1200): " + str(es_peso_util(1200)))
print("es_peso_util(800): " + str(es_peso_util(800)))
print("4.3")
print("sirve_pino(0.5): " + str(sirve_pino(0.5)))
print("sirve_pino(2): " + str(sirve_pino(2)))
print("sirve_pino(5): " + str(sirve_pino(5)))
print("4.4")

print("-----")

print("5.")
print("5.1")
print("devolver_el_doble_si_es_par(3): " + str(devolver_el_doble_si_es_par(3)))
print("devolver_el_doble_si_es_par(4): " + str(devolver_el_doble_si_es_par(4)))
print("5.2")
print("devolver_valor_si_es_par_sino_el_que_sigue_1(3): " + str(devolver_valor_si_es_par_sino_el_que_sigue_1(3)))
print("devolver_valor_si_es_par_sino_el_que_sigue_1(8): " + str(devolver_valor_si_es_par_sino_el_que_sigue_1(8)))
print("devolver_valor_si_es_par_sino_el_que_sigue_2(3): " + str(devolver_valor_si_es_par_sino_el_que_sigue_2(3)))
print("devolver_valor_si_es_par_sino_el_que_sigue_2(8): " + str(devolver_valor_si_es_par_sino_el_que_sigue_2(8)))
print("5.3")
print("devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_1(1): " + str(devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_1(1)))
print("devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_1(6): " + str(devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_1(6)))
print("devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_1(18): " + str(devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_1(18)))
print("devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_2(1): " + str(devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_2(1)))
print("devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_2(6): " + str(devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_2(6)))
print("devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_2(18): " + str(devolver_el_doble_si_es_multiplo3_el_triple_si_es_multiplo9_2(18)))
print("5.4")
print('nombre_tiene_muchas_letras("Juan")' + nombre_tiene_muchas_letras("Juan"))
print('nombre_tiene_muchas_letras("Pedro")' + nombre_tiene_muchas_letras("Pedro"))
print('nombre_tiene_muchas_letras("Roberta")' + nombre_tiene_muchas_letras("Roberta"))
print("5.5")
print('trabaja_o_vacaciona("F", 8): ' + trabaja_o_vacaciona("F", 8))
print('trabaja_o_vacaciona("M", 8): ' + trabaja_o_vacaciona("M", 8))
print('trabaja_o_vacaciona("M", 18): ' + trabaja_o_vacaciona("M", 18))
print('trabaja_o_vacaciona("F", 30): ' + trabaja_o_vacaciona("F", 30))
print('trabaja_o_vacaciona("F", 60): ' + trabaja_o_vacaciona("F", 60))
print('trabaja_o_vacaciona("F", 61): ' + trabaja_o_vacaciona("F", 61))
print('trabaja_o_vacaciona("M", 64): ' + trabaja_o_vacaciona("M", 64))
print('trabaja_o_vacaciona("M", 65): ' + trabaja_o_vacaciona("M", 65))
print('trabaja_o_vacaciona("M", 70): ' + trabaja_o_vacaciona("M", 70))

# print("6.")
# print("6.2")
# print("imprimir_pares_entre_10_y_40(): ")
# imprimir_pares_entre_10_y_40()