from p8 import *

print("1.")
print("1.1")
print("pertenece1([], 1)")
print(pertenece1([], 1))
print("pertenece1([1], 1)")
print(pertenece1([1], 1))
print("pertenece1([1,2,3], 3)")
print(pertenece1([1,2,3], 3))
print("pertenece1([1,2,3], 4)")
print(pertenece1([1,2,3], 4))
print("--")
print("pertenece2([], 1)")
print(pertenece2([], 1))
print("pertenece2([1], 1)")
print(pertenece2([1], 1))
print("pertenece2([1,2,3], 3)")
print(pertenece2([1,2,3], 3))
print("pertenece2([1,2,3], 4)")
print(pertenece2([1,2,3], 4))
print("--")
print("pertenece3([], 1)")
print(pertenece3([], 1))
print("pertenece3([1], 1)")
print(pertenece3([1], 1))
print("pertenece3([1,2,3], 3)")
print(pertenece3([1,2,3], 3))
print("pertenece3([1,2,3], 4)")
print(pertenece3([1,2,3], 4))

print("-----")

print("1.2")
print("divide_a_todos([], 1)")
print(divide_a_todos([], 1))
print("divide_a_todos([7], 2)")
print(divide_a_todos([7], 2))
print("divide_a_todos([2], 2)")
print(divide_a_todos([2], 2))
print("divide_a_todos([4,3], 2)")
print(divide_a_todos([4,3], 2))
print("divide_a_todos([4,8,12], 2)")
print(divide_a_todos([4,8,12], 2))

print("-----")

print("1.3")
print("sumaTotal([])")
print(sumaTotal([]))
print("sumaTotal([1])")
print(sumaTotal([1]))
print("sumaTotal([1,2,3]")
print(sumaTotal([1,2,3]))

print("-----")

print("1.4")
print("ordenados([])")
print(ordenados([]))
print("ordenados([1])")
print(ordenados([1]))
print("ordenados([1,2,2])")
print(ordenados([1,2,2]))
print("ordenados([1,2,3])")
print(ordenados([1,2,3]))
print("ordenados([1,3,2])")
print(ordenados([1,3,2]))

print("-----")

print("1.5")
print("alguna_mas_larga_que_7([])")
print(alguna_mas_larga_que_7([]))
print('alguna_mas_larga_que_7(["casa", "carpa", "hotel"])')
print(alguna_mas_larga_que_7(["casa", "carpa", "hotel"]))
print('alguna_mas_larga_que_7(["casas", "carpas", "hoteles", "mansiones"])')
print(alguna_mas_larga_que_7(["casas", "carpas", "hoteles", "mansiones"]))

print("-----")

print("1.6")
print('es_palindroma("")')
print(es_palindroma(""))
print('es_palindroma("a")')
print(es_palindroma("a"))
print('es_palindroma("menem")')
print(es_palindroma("menem"))
print('es_palindroma("mennem")')
print(es_palindroma("mennem"))
print('es_palindroma("hereje")')
print(es_palindroma("hereje"))

print("-----")

print("1.7")
print('es_contraseña_segura("123")')
print(es_contraseña_segura("123"))
print('es_contraseña_segura("jaja")')
print(es_contraseña_segura("jaja"))
print('es_contraseña_segura("colores123")')
print(es_contraseña_segura("colores123"))
print('es_contraseña_segura("coloreS")')
print(es_contraseña_segura("coloreS"))
print('es_contraseña_segura("dIAmANtes12")')
print(es_contraseña_segura("dIAmANtes12"))
print('es_contraseña_segura("dIAmANtes12!")')
print(es_contraseña_segura("dIAmANtes12!"))

print("-----")

print("1.8")
print("saldo_actual([('I', 2000), ('R', 20), ('R', 1000), ('I', 300)])")
print(saldo_actual([('I', 2000), ('R', 20), ('R', 1000), ('I', 300)]))

print("-----")

print("1.9")
print('tiene_3_vocales_distintas("casa")')
print(tiene_3_vocales_distintas("casa"))
print('tiene_3_vocales_distintas("lejanos")')
print(tiene_3_vocales_distintas("lejanos"))

print("-----")

print("2")
print("2.1")
s = [1,2,3,4]
print("s: ",  s)
colocar_ceros_en_pares_inout(s)
print("s: ",  s)

print("-----")

print("2.2")
s = [1,2,3,4]
print("s: ",  s)
s_modificada = colocar_ceros_en_pares_in(s)
print("s: ",  s)
print("s_modificada: ",  s_modificada)

print("-----")

print("2.3")
print('elimina_vocales("aeiou")')
print(elimina_vocales("aeiou"))
print('elimina_vocales("bcdfg")')
print(elimina_vocales("bcdfg"))
print('elimina_vocales("murcielago")')
print(elimina_vocales("murcielago"))

print("-----")

print("2.4")
print('reemplaza_vocales("aeiou")')
print(reemplaza_vocales("aeiou"))
print('reemplaza_vocales("bcdfg")')
print(reemplaza_vocales("bcdfg"))
print('reemplaza_vocales("murcielago")')
print(reemplaza_vocales("murcielago"))

print("-----")

print("2.5")
print('da_vuelta_str("aeiou")')
print(da_vuelta_str("aeiou"))
print('da_vuelta_str("bcdfg")')
print(da_vuelta_str("bcdfg"))
print('da_vuelta_str("murcielago")')
print(da_vuelta_str("murcielago"))

print("-----")

print("3.")
print("3.1")
print("Descomentar las líneas correspondientes para probar.")
# nombres = construye_lista_de_nombres()
# print(nombres)

print("-----")

print("3.2")
print("Descomentar las líneas correspondientes para probar.")
# historial = construye_historial_de_monedero()
# print(historial)

print("-----")

print("3.3")
print("Descomentar las líneas correspondientes para probar.")
# historial = siete_y_medio()
# print(historial)

print("-----")

print("4.")
print("4.1")
print("pertenece_a_cada_uno([], 1)")
print(pertenece_a_cada_uno([], 1))
print("pertenece_a_cada_uno([[2,3], [4,5,6]], 1)")
print(pertenece_a_cada_uno([[2,3], [4,5,6]], 1))
print("pertenece_a_cada_uno([[1,2], [4,5,6]], 1)")
print(pertenece_a_cada_uno([[1,2], [4,5,6]], 1))
print("pertenece_a_cada_uno([[1,2,3,4], [1,3,6]], 1)")
print(pertenece_a_cada_uno([[1,2,3,4], [1,3,6]], 1))

print("-----")

print("4.2")
print("es_matriz([])")
print(es_matriz([]))
print("es_matriz([[], [2,2,2], [3,3,3]])")
print(es_matriz([[], [2,2,2], [3,3,3]]))
print("es_matriz([[1,1,1], [2,2,2], [3,3,3]])")
print(es_matriz([[1,1,1], [2,2,2], [3,3,3]]))

print("-----")

print("4.3")
print("filas_ordenadas([[1,1,1], [2,2], [3]])")
print(filas_ordenadas([[1,1,1], [2,2], [3]]))
print("filas_ordenadas([[1,2,3,4], [2,1,5], [3,8]])")
print(filas_ordenadas([[1,2,3,4], [2,1,5], [3,8]]))

print("-----")

print("4.4")
# print(elevar_matriz(2,2))
# print(elevar_matriz(3,2))
# print(elevar_matriz(2,3))
print(elevar_matriz(25,25))